name: Profile View Boost - BabaYaga

on:
  schedule:
    - cron: "*/10 * * * *" # Roda a cada 10 minutos para não estressar o IP
  workflow_dispatch:

jobs:
  boost:
    runs-on: ubuntu-latest
    steps:
      - name: Boost Profile Views (Proxy Strategy)
        run: |
          URL_BABA="https://komarev.com/ghpvc/?username=BabaYaga-RU&color=00FF41&style=for-the-badge"
          
          echo "Buscando lista de proxies..."
          curl -s "https://api.proxyscrape.com/v2/?request=displayproxies&protocol=http&timeout=1000&country=all&ssl=all&anonymity=all" > proxies.txt
          
          echo "Iniciando rajada..."
          count=0
          while read -r line && [ $count -lt 60 ]; do
            UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            
            # Dispara em paralelo focado apenas no seu user
            curl -x "$line" -A "$UA" -s -m 5 "$URL_BABA" > /dev/null && echo "Hit via $line" &
            
            count=$((count+1))
            sleep 0.1
          done < proxies.txt
          
          wait
          echo "Boost finalizado."
